apiVersion: v1
kind: Service
metadata:
  name: redis-enterprise-lb
  labels:
    app: redis-enterprise-lb
spec:
  ports:
    - name: ui
      port: 8443
      targetPort: 8443
      protocol: TCP
    - name: redis
      port: 26379
      targetPort: 26379
      protocol: TCP
  selector:
    app: redis-enterprise
